---
functional:
  - пользователь должен иметь возможность создать игру
  - пользователь должен иметь возможность присоединиться к открытой игре
  - пользователь должен иметь возможность присоединиться к игре по ссылке
  - пользователь должен иметь возможность зайти в запущенную игру в качестве зрителя
  - пользователь должен иметь возможность выбрать язык программирования в задаче - JavaScript, PHP, Python и Ruby
  - пользователь должен иметь возможность видеть свой код и код соперника в реальном времени
  - пользователь должен иметь возможность видеть результаты запуска тестов
  - пользователь должен иметь возможность общаться с соперником и зрителями в чате
  - пользователь должен иметь возможность установить расширение для Chrome, чтобы следить за открытыми играми
non-functional:
  - сайт должен быть разработан с учетом удобства использования и оптимизирован для скорости работы
  - сайт должен быть безопасным и защищать данные пользователя
  - сайт должен быть удобным на мобильном устройстве
  - сайт должен быть протестирован на совместимость с последними версиями браузеров
  - сайт должен быть способен обрабатывать большое количество трафика (например, 1000 одновременных пользователей)
implicit:
  - возможность регистрации и авторизации пользователя
  - на каких языках должен отображаться сайт
  - если пользователь побеждает, что он видит у себя на экране
  - если пользователь проигрывает, что он видит у себя на экране
  - при создании игры можно ли будет добавлять свои игры, если да, то каким образом и в каком формате
  - игра будет на время или нет
  - можно ли поставить игру на паузу
  - можно ли предварительно закончить игру
  - чат поддерживает только текст, либо можно использовать смайлики и прикреплять вложения
  - есть ли срок действия у созданной игры
  - сохраняются ли завершенные игры и можно ли их просмотреть
